## Config file for sample.py project
title = 'PhantomTest'
sessionId = 'phantom'
location = 'LCNI'

# Scan info 
minExpectedDicomSize = 100000       
refBoldScanNum = 7                                  # refbold 
strucScanNum = 6                                    # sturc
scanNum = [11]                                      # Functional EPI 
numTR_func_run = 160                                # Numer of TR!! NOT SECOND!! 
subjectName = 'sub_test'                            # This will be part of the folder name, need to be consistent with the scanner input. 
datestr = '20211026'                                # This will be part of the folder name, need to be consistent with the scanner input. 
sessionNum = 2                                      # the number of time the participant being scanned
runNum = 1                                          # the number of functional run in this session. 
dicomNamePattern = "001_{SCAN:06d}_{TR:06d}.dcm" 
roi = ["/home/rtfmri/Documents/rt-cloud/projects/phantom_test/data/roi/rsc_roi_big_resampled.nii.gz"]      # standard space ROI that we care about. 


## Directory 
imgDir = '/home/rtfmri/Documents/bridge'
codeDir = '/home/rtfmri/Documents/rt-cloud/projects/phantom_test'  


## Plotting info. 
plotTitle = 'Realtime Plot'
plotXLabel = 'Sample #'
plotYLabel = 'Value'
plotXRangeLow = 0
plotXRangeHigh = 333
plotYRangeLow = -1
plotYRangeHigh = 1
plotAutoRangeX = false
plotAutoRangeY = true